1) Usando a biblioteca numpy e o módulo datasets da biblioteca sklearn, carregue o dataset iris e apresente os rótulos das classes de iris, as dimensões e conteúdo das matrizes de treino e de classificação.

In [42]:
import numpy as np
from sklearn import datasets

ds = datasets.load_iris()

print(ds.target_names)
print(ds.data.shape)

print(ds.data)
print(ds.target)

['setosa' 'versicolor' 'virginica']
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7. 

2) Crie uma função em python que receba um vetor com classificações dos exemplos de um dataset e apresente a distribuição de probabilidades de cada classe.

In [21]:
def probability_distribution(classifications):
    count = {}
    
    for classification in classifications:
        if classification in count:
            count[classification] += 1
        else:
            count[classification] = 1

    total_count = len(classifications)
    
    probabilities = {}
    for classification, count in count.items():
        probabilities[classification] = count / total_count
    
    return probabilities

print(probability_distribution(ds.target))


{np.int64(0): 0.3333333333333333, np.int64(1): 0.3333333333333333, np.int64(2): 0.3333333333333333}


3) Selecione aleatoriamente 10 exemplos da base iris para teste e use os demais exemplos para treinar um modelo usando a técnica do vizinho mais próximo. Apresente a classificação real e a classificação obtida pelo modelo para os 10 exemplos de teste.

In [36]:
np.random.seed(0)
indices = np.random.permutation(len(ds.data))
iris_X_train = ds.data[indices[:-10]]
iris_X_test = ds.data[indices[-10:]]
iris_y_train = ds.target[indices[:-10]]
iris_y_test = ds.target[indices[-10:]]

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(iris_X_train, iris_y_train)
print(iris_y_test)
print(knn.predict(iris_X_test))


[1 1 1 0 0 0 2 1 2 0]
[1 2 1 0 0 0 2 1 2 0]


4) Usando o modulo model_selection do sklearn, selecione aleatoriamente 40% dos exemplos da base iris para teste e use os demais exemplos para treinar um modelo baseado na técnica do vizinho mais próximo. Apresente as dimensões das matrizes de treino e classificação dos conjuntos de treino e teste, a classificação real e a classificação obtida pelo modelo para os exemplos de teste e a acurácia alcançada.

In [40]:
from sklearn import model_selection

np.random.seed(0)
iris_X_train, iris_X_test, iris_y_train, iris_y_test = model_selection.train_test_split(
    ds.data, ds.target, test_size=0.4
)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(iris_X_train, iris_y_train)

print(iris_X_train.shape)
print(iris_X_test.shape)
print(iris_y_train.shape)
print(iris_y_test.shape)

print(iris_y_test)
print(knn.predict(iris_X_test))

from sklearn.metrics import accuracy_score
print(accuracy_score(iris_y_test, knn.predict(iris_X_test)))

(90, 4)
(60, 4)
(90,)
(60,)
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 1 1 1 2 1 2]
0.9166666666666666


5) Usando o modulo metrics do sklearn, apresente a matriz de confusão do exercício anterior.

In [41]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(iris_y_test, knn.predict(iris_X_test)))

[[16  0  0]
 [ 0 22  1]
 [ 0  4 17]]


6) Ainda usando o modulo metrics do sklearn, utilize as predições do exercício anterior, para apresentar a acurácia, a acurácia balanceada, as precisões macro, micro e balanceada, as revocações macro, micro e balanceada, e as medidas f macro, micro e balanceada.

In [43]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score

print(accuracy_score(iris_y_test, knn.predict(iris_X_test)))
print(balanced_accuracy_score(iris_y_test, knn.predict(iris_X_test)))

print(precision_score(iris_y_test, knn.predict(iris_X_test), average='macro'))
print(precision_score(iris_y_test, knn.predict(iris_X_test), average='micro'))
print(precision_score(iris_y_test, knn.predict(iris_X_test), average='weighted'))

print(precision_score(iris_y_test, knn.predict(iris_X_test), average='macro'))
print(precision_score(iris_y_test, knn.predict(iris_X_test), average='micro'))
print(precision_score(iris_y_test, knn.predict(iris_X_test), average='weighted'))

print(precision_score(iris_y_test, knn.predict(iris_X_test), average='macro'))
print(precision_score(iris_y_test, knn.predict(iris_X_test), average='micro'))
print(precision_score(iris_y_test, knn.predict(iris_X_test), average='weighted'))

0.9166666666666666
0.9220151828847482
0.9301994301994302
0.9166666666666666
0.9215811965811966
0.9301994301994302
0.9166666666666666
0.9215811965811966
0.9301994301994302
0.9166666666666666
0.9215811965811966


7) Aplique o método de reamostragem de resubstituição no dataset iris usando o classificador vizinho mais próximo e apresente a matriz de confusão dos resultados.

8) Aplique o método de reamostragem de divisão percentual no dataset iris com 50% de exemplos selecionados aleatoriamente para treino e 50% para teste e use o classificador vizinho mais próximo para apresentar a matriz de confusão dos resultados.

9) Aplique o método de reamostragem de validação cruzada com 5 folds no dataset iris com o classificador vizinho mais próximo e apresente média, desvio padrão, intervalo de confiança a 95% da acurácia e a matriz de confusão dos resultados.

10) Aplique o método de reamostragem de validação cruzada com 5 folds no dataset iris com o classificador vizinho mais próximo e apresente média e desvio padrão da acurácia, precisão macro, revocação macro e medida f dos resultados.

11) Aplique o método de reamostragem do um excluído no dataset iris com o classificador vizinho mais próximo e apresente média, desvio padrão e intervalo de confiança a 95% da acurácia dos resultados.

12) Aplique o método de reamostragem de validação cruzada com 10 folds no dataset iris com o classificador de k vizinhos mais próximos fazendo uma busca em grade nos valores de k (k = 1, 3 e 5) e apresente a melhor média de acurácia alcançada e os valores dos hiperparâmetros do método que atingiu essa melhor média de acurácia. Apresente também a lista de informações disponíveis para acessar após a realização da busca em grade, os resultados de acurácia obtidos por cada modelo em cada fold e, por fim, a média da acurácia alcançada cada modelo ao final da validação cruzada.

13) Aplique o método de reamostragem de validação cruzada aninhada repetida com 6 repetições de validação cruzada com 5 folds no ciclo externo e 4 folds no ciclo interno no dataset iris com o classificador de k vizinhos mais próximos fazendo uma busca em grade nos valores de k (k = 1, 3 e 5). Apresente os 30 resultados de acurácia alcançados em cada fold de teste, a média, o desvio padrão e o intervalo de confiança a 95% dessas acurácias.

14) Repita o procedimento do exercício anterior trocando o classificador de K vizinhos mais próximos pelo classificador de árvore de decisão fazendo a busca em grade com os valores 2 e 3 para o hiperparâmetro max_depth e 2 e 4 para o hiperparâmetro min_samples_split.

15) Compare estatisticamente os resultados alcançados de acurácia pelos classificadores K vizinhos mais próximos e árvore de decisão obtidos nos dois últimos exercícios usando os testes de hipótese t pareado para amostras correlacionadas e wilcoxon.

16) Implemente uma função que aplique a correção de Nadeau e Bengio (usando a equação relatada em https://www.cs.waikato.ac.nz/~eibe/pubs/bouckaert_and_frank.pdf) para o teste de hipótese t pareado para amostras correlacionadas e a utilize para realizar novamente a comparação estatística do exercício anterior.